name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build VuePress
      run: |
        yarn && yarn vuepress build um-stripe
    - name: Commit files
      run: |
        cd um-stripe/dist/
        mv * deploy/um-stripe | mkdir deploy/um-stripe
        cd deploy
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -a -m "Deploy Stripe Docs"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DOCS_V3_ACTION_SECRET }}
        repository: ultimatemember/docs-v3
        branch: gh-pages
        